# Generated by Django 4.2.7 on 2023-12-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_profiles_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='age',
            field=models.IntegerField(blank=True, max_length=10, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='land',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна'),
        ),
    ]
