# Generated by Django 4.2.7 on 2023-12-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_profiles_age_alter_profiles_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='age',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='land',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
    ]
